"""默认内容表。

按《怪兽形态设计》《抽卡系统》《开局预设》《掉落系统》《成就系统》的规则落地的
初始版本。所有数值为基准值，可通过 patch 调整并写入 ``config_version``。
"""

from __future__ import annotations

from .contract import ConfigBundle, validate_config_bundle

# =============================================================================
# 关卡 —《关卡与计分系统》§4
# =============================================================================
DEFAULT_STAGES: dict[str, dict] = {
    "stage_1": {
        "id": "stage_1",
        "name": "第一关",
        "clear_score": 1200,
        "hp_multiplier": 1.00,
        "damage_multiplier": 1.00,
        "armor_bonus": 0,
        "spawn_budget_multiplier": 1.00,
        "elite_base_chance": 0.02,
        "max_elite_chance": 0.25,
        "enemy_pool": ["spinner_chaser", "wingblade_sprinter", "lantern_shooter", "crystal_sniper"],
        "enemy_weights": [0.43, 0.15, 0.26, 0.16],
    },
    "stage_2": {
        "id": "stage_2",
        "name": "第二关",
        "clear_score": 2600,
        "hp_multiplier": 1.50,
        "damage_multiplier": 1.25,
        "armor_bonus": 5,
        "spawn_budget_multiplier": 1.20,
        "elite_base_chance": 0.06,
        "max_elite_chance": 0.25,
        "enemy_pool": [
            "spinner_chaser",
            "wingblade_sprinter",
            "shellguard_heavy",
            "lantern_shooter",
            "crystal_sniper",
        ],
        "enemy_weights": [0.25, 0.16, 0.17, 0.25, 0.17],
    },
    "stage_3": {
        "id": "stage_3",
        "name": "第三关",
        "clear_score": 4800,
        "hp_multiplier": 2.20,
        "damage_multiplier": 1.55,
        "armor_bonus": 12,
        "spawn_budget_multiplier": 1.45,
        "elite_base_chance": 0.10,
        "max_elite_chance": 0.25,
        "enemy_pool": [
            "spinner_chaser",
            "wingblade_sprinter",
            "shellguard_heavy",
            "lantern_shooter",
            "multinode_spreader",
            "minelayer_bomber",
            "crystal_sniper",
        ],
        "enemy_weights": [0.16, 0.14, 0.15, 0.18, 0.13, 0.10, 0.14],
    },
    "stage_4": {
        "id": "stage_4",
        "name": "第四关",
        "clear_score": 6800,
        "hp_multiplier": 2.85,
        "damage_multiplier": 1.85,
        "armor_bonus": 18,
        "spawn_budget_multiplier": 1.70,
        "elite_base_chance": 0.13,
        "max_elite_chance": 0.30,
        "enemy_pool": [
            "spinner_chaser", "wingblade_sprinter", "shellguard_heavy",
            "lantern_shooter", "multinode_spreader", "minelayer_bomber", "crystal_sniper",
            "mine_leech", "rail_turret",
        ],
        "enemy_weights": [0.11, 0.11, 0.13, 0.14, 0.12, 0.10, 0.11, 0.09, 0.09],
    },
    "stage_5": {
        "id": "stage_5",
        "name": "第五关",
        "clear_score": 9000,
        "hp_multiplier": 3.55,
        "damage_multiplier": 2.20,
        "armor_bonus": 25,
        "spawn_budget_multiplier": 1.95,
        "elite_base_chance": 0.16,
        "max_elite_chance": 0.35,
        "enemy_pool": [
            "spinner_chaser", "wingblade_sprinter", "shellguard_heavy",
            "lantern_shooter", "multinode_spreader", "minelayer_bomber", "crystal_sniper",
            "mine_leech", "rail_turret",
        ],
        "enemy_weights": [0.09, 0.10, 0.14, 0.14, 0.14, 0.11, 0.12, 0.08, 0.08],
    },
    "endless": {
        "id": "endless",
        "name": "无尽模式",
        "clear_score": None,  # 无尽无终点
        "cycle_score": 5000,
        "hp_multiplier": 2.80,
        "damage_multiplier": 1.80,
        "armor_bonus": 18,
        "spawn_budget_multiplier": 1.60,
        "elite_base_chance": 0.12,
        "max_elite_chance": 0.35,
        "enemy_pool": [
            "spinner_chaser",
            "wingblade_sprinter",
            "shellguard_heavy",
            "lantern_shooter",
            "multinode_spreader",
            "minelayer_bomber",
            "crystal_sniper",
            "mine_leech",
            "rail_turret",
        ],
        "enemy_weights": [0.12, 0.12, 0.11, 0.14, 0.12, 0.11, 0.12, 0.08, 0.08],
    },
}


# =============================================================================
# 敌人原型 —《怪兽形态设计》§2 +《怪兽要求》§3
# 生命为 1 关、0 分钟、普通难度的基准。
# =============================================================================
DEFAULT_ENEMIES: dict[str, dict] = {
    "spinner_chaser": {
        "id": "spinner_chaser",
        "archetype": "chaser_melee",
        "display_name": "旋刃追击者",
        "max_hp": 40,
        "move_speed": 110,
        "contact_damage": 8,
        "armor": 0,
        "attack_range": 50,
        "attack_interval": 0.8,
        "windup_time": 0.4,
        "cooldown_time": 0.5,
        "xp_value": 2,
        "base_kill_score": 10,
        "drop_table_id": "std_drops",
        "collision_radius": 18,
        "tags": ["melee"],
    },
    "wingblade_sprinter": {
        "id": "wingblade_sprinter",
        "archetype": "fast_melee",
        "display_name": "翼刃疾行者",
        "max_hp": 28,
        "move_speed": 175,
        "contact_damage": 7,
        "armor": 0,
        "attack_range": 80,
        "attack_interval": 0.6,
        "windup_time": 0.3,
        "cooldown_time": 0.35,
        "xp_value": 2,
        "base_kill_score": 12,
        "drop_table_id": "std_drops",
        "collision_radius": 14,
        "tags": ["melee", "fast"],
    },
    "shellguard_heavy": {
        "id": "shellguard_heavy",
        "archetype": "heavy_melee",
        "display_name": "甲壳重卫",
        "max_hp": 140,
        "move_speed": 70,
        "contact_damage": 14,
        "armor": 4,
        "attack_range": 60,
        "attack_interval": 1.2,
        "windup_time": 0.55,
        "cooldown_time": 0.65,
        "xp_value": 6,
        "base_kill_score": 25,
        "drop_table_id": "std_drops",
        "collision_radius": 26,
        "tags": ["melee", "heavy"],
    },
    "lantern_shooter": {
        "id": "lantern_shooter",
        "archetype": "ranged",
        "display_name": "灯火射手",
        "max_hp": 65,
        "move_speed": 95,
        "contact_damage": 6,
        "armor": 0,
        "attack_range": 620,
        "attack_interval": 1.45,
        "windup_time": 0.45,
        "cooldown_time": 0.7,
        "projectile_speed": 460,
        "projectile_lifetime": 2.0,
        "projectile_damage": 9,
        "projectile_radius": 6,
        "ideal_distance": 520,
        "xp_value": 4,
        "base_kill_score": 15,
        "drop_table_id": "std_drops",
        "collision_radius": 18,
        "tags": ["ranged"],
    },
    "crystal_sniper": {
        "id": "crystal_sniper",
        "archetype": "ranged_sniper",
        "display_name": "水晶狙击手",
        "max_hp": 78,
        "move_speed": 88,
        "contact_damage": 7,
        "armor": 1,
        "attack_range": 760,
        "attack_interval": 2.6,
        "windup_time": 0.9,
        "cooldown_time": 1.15,
        "projectile_speed": 760,
        "projectile_lifetime": 1.7,
        "projectile_damage": 16,
        "projectile_radius": 7,
        "ideal_distance": 610,
        "xp_value": 6,
        "base_kill_score": 24,
        "drop_table_id": "std_drops",
        "collision_radius": 20,
        "tags": ["ranged", "sniper"],
    },
    "multinode_spreader": {
        "id": "multinode_spreader",
        "archetype": "spreader_ranged",
        "display_name": "多节点散射者",
        "max_hp": 90,
        "move_speed": 80,
        "contact_damage": 8,
        "armor": 1,
        "attack_range": 560,
        "attack_interval": 1.9,
        "windup_time": 0.55,
        "cooldown_time": 1.0,
        "projectile_speed": 360,
        "projectile_lifetime": 1.8,
        "projectile_damage": 7,
        "projectile_radius": 6,
        "spread_arc_deg": 60,
        "spread_projectile_count": 4,
        "ideal_distance": 470,
        "xp_value": 5,
        "base_kill_score": 22,
        "drop_table_id": "std_drops",
        "collision_radius": 22,
        "tags": ["ranged", "spreader"],
    },
    "minelayer_bomber": {
        "id": "minelayer_bomber",
        "archetype": "bomber",
        "display_name": "布雷者",
        "max_hp": 75,
        "move_speed": 100,
        "contact_damage": 7,
        "armor": 0,
        "attack_range": 360,
        "attack_interval": 3.0,
        "windup_time": 0.6,
        "cooldown_time": 2.0,
        "drops_bomb": True,
        "bomb_spawn_interval": 2.5,
        "xp_value": 5,
        "base_kill_score": 20,
        "drop_table_id": "std_drops",
        "collision_radius": 20,
        "tags": ["ranged", "hazard"],
    },
    "mine_leech": {
        "id": "mine_leech",
        "archetype": "chaser_melee",
        "display_name": "矿脉寄生体",
        "max_hp": 52,
        "move_speed": 128,
        "contact_damage": 10,
        "armor": 2,
        "attack_range": 54,
        "attack_interval": 0.92,
        "windup_time": 0.34,
        "cooldown_time": 0.48,
        "xp_value": 4,
        "base_kill_score": 18,
        "drop_table_id": "std_drops",
        "collision_radius": 19,
        "tags": ["melee", "mineral"],
    },
    "rail_turret": {
        "id": "rail_turret",
        "archetype": "ranged_sniper",
        "display_name": "轨道炮台",
        "max_hp": 96,
        "move_speed": 42,
        "contact_damage": 8,
        "armor": 5,
        "attack_range": 820,
        "attack_interval": 2.2,
        "windup_time": 0.82,
        "cooldown_time": 1.05,
        "projectile_speed": 900,
        "projectile_lifetime": 1.55,
        "projectile_damage": 22,
        "projectile_radius": 8,
        "ideal_distance": 650,
        "xp_value": 8,
        "base_kill_score": 32,
        "drop_table_id": "std_drops",
        "collision_radius": 24,
        "tags": ["ranged", "sniper", "turret"],
    },
}


# =============================================================================
# 武器 —《攻击视野与距离》§4 +《武器切换系统》
# =============================================================================
DEFAULT_WEAPONS: dict[str, dict] = {
    "w_melee_blade": {
        "id": "w_melee_blade",
        "display_name": "迅捷砍刀",
        "archetype": "melee_aoe",
        "base_damage": 18,
        "attack_interval": 0.55,
        "sense_radius": 240,
        "attack_range": 150,
        "attack_arc_deg": 120,
        "fire_tolerance_deg": 60,
        "windup_time": 0.10,
        "projectile_speed": 0,
        "projectile_lifetime": 0,
        "projectile_count": 1,
        "penetration": 1,
        "is_melee": True,
        "crit_chance": 0.05,
        "crit_multiplier": 1.5,
    },
    "w_rifle_precise": {
        "id": "w_rifle_precise",
        "display_name": "冰雹步枪",
        "archetype": "ranged_single",
        "base_damage": 28,
        "attack_interval": 0.50,
        "sense_radius": 780,
        "attack_range": 680,
        "attack_arc_deg": 25,
        "fire_tolerance_deg": 12,
        "windup_time": 0.10,
        "projectile_speed": 720,
        "projectile_lifetime": 1.0,
        "projectile_count": 1,
        "penetration": 1,
        "is_melee": False,
        "requires_line_of_sight": True,
        "crit_chance": 0.10,
        "crit_multiplier": 1.6,
    },
    "w_shotgun_spread": {
        "id": "w_shotgun_spread",
        "display_name": "散射霰弹",
        "archetype": "ranged_spread",
        "base_damage": 9,
        "attack_interval": 0.42,
        "sense_radius": 620,
        "attack_range": 500,
        "attack_arc_deg": 45,
        "fire_tolerance_deg": 30,
        "windup_time": 0.10,
        "projectile_speed": 600,
        "projectile_lifetime": 0.9,
        "projectile_count": 4,
        "penetration": 1,
        "is_melee": False,
        "requires_line_of_sight": True,
        "spread_arc_deg": 45,
        "crit_chance": 0.06,
        "crit_multiplier": 1.5,
    },
    "w_orbiter_omni": {
        "id": "w_orbiter_omni",
        "display_name": "环绕哨兵",
        "archetype": "orbit_omni",
        "base_damage": 14,
        "attack_interval": 0.20,
        "sense_radius": 300,
        "attack_range": 180,
        "attack_arc_deg": 360,
        "fire_tolerance_deg": 90,
        "windup_time": 0.05,
        "projectile_speed": 0,
        "projectile_lifetime": 0,
        "projectile_count": 1,
        "penetration": 1,
        "is_melee": True,
        "omnidirectional": True,
        "crit_chance": 0.03,
        "crit_multiplier": 1.4,
    },
    "w_laser_charge": {
        "id": "w_laser_charge",
        "display_name": "光束矩阵",
        "archetype": "beam",
        "base_damage": 22,
        "attack_interval": 0.35,
        "sense_radius": 720,
        "attack_range": 700,
        "attack_arc_deg": 20,
        "fire_tolerance_deg": 8,
        "windup_time": 0.16,
        "projectile_speed": 1200,
        "projectile_lifetime": 0.6,
        "projectile_count": 1,
        "penetration": 4,
        "is_melee": False,
        "requires_line_of_sight": True,
        "crit_chance": 0.08,
        "crit_multiplier": 1.7,
    },
    "w_laser_cannon": {
        "id": "w_laser_cannon",
        "display_name": "激光炮",
        "archetype": "heavy_beam",
        "base_damage": 96,
        "attack_interval": 1.35,
        "sense_radius": 900,
        "attack_range": 860,
        "attack_arc_deg": 18,
        "fire_tolerance_deg": 10,
        "windup_time": 0.32,
        "projectile_speed": 920,
        "projectile_lifetime": 1.15,
        "projectile_radius": 15,
        "projectile_count": 1,
        "penetration": 7,
        "beam_width": 18,
        "is_melee": False,
        "requires_line_of_sight": True,
        "crit_chance": 0.12,
        "crit_multiplier": 1.9,
    },
    "w_arcane_orb": {
        "id": "w_arcane_orb",
        "display_name": "奥术回响",
        "archetype": "orb",
        "base_damage": 30,
        "attack_interval": 0.65,
        "sense_radius": 700,
        "attack_range": 540,
        "attack_arc_deg": 30,
        "fire_tolerance_deg": 15,
        "windup_time": 0.12,
        "projectile_speed": 480,
        "projectile_lifetime": 1.5,
        "projectile_count": 1,
        "penetration": 2,
        "is_melee": False,
        "bounces": True,
        "crit_chance": 0.07,
        "crit_multiplier": 1.6,
    },
    "w_great_cleaver": {
        "id": "w_great_cleaver",
        "display_name": "裂地大砍刀",
        "archetype": "heavy_melee",
        "base_damage": 78,
        "attack_interval": 1.45,
        "sense_radius": 330,
        "attack_range": 245,
        "attack_arc_deg": 155,
        "fire_tolerance_deg": 90,
        "windup_time": 0.38,
        "projectile_speed": 0,
        "projectile_lifetime": 0,
        "projectile_count": 1,
        "penetration": 12,
        "is_melee": True,
        "clears_enemy_bullets": True,
        "crit_chance": 0.08,
        "crit_multiplier": 2.0,
    },
    "w_ricochet_ball": {
        "id": "w_ricochet_ball",
        "display_name": "棱镜弹球",
        "archetype": "ricochet_orb",
        "base_damage": 34,
        "attack_interval": 0.78,
        "sense_radius": 820,
        "attack_range": 760,
        "attack_arc_deg": 30,
        "fire_tolerance_deg": 18,
        "windup_time": 0.14,
        "projectile_speed": 560,
        "projectile_lifetime": 6.0,
        "projectile_radius": 12,
        "projectile_count": 1,
        "penetration": 8,
        "bounces": True,
        "bounce_count": 7,
        "is_melee": False,
        "crit_chance": 0.06,
        "crit_multiplier": 1.6,
    },
    "w_thunder_daggers": {
        "id": "w_thunder_daggers",
        "display_name": "雷鸣短刃",
        "archetype": "fast_melee",
        "base_damage": 16,
        "attack_interval": 0.24,
        "sense_radius": 280,
        "attack_range": 135,
        "attack_arc_deg": 95,
        "fire_tolerance_deg": 70,
        "windup_time": 0.04,
        "projectile_speed": 0,
        "projectile_lifetime": 0,
        "projectile_count": 1,
        "penetration": 2,
        "is_melee": True,
        "crit_chance": 0.16,
        "crit_multiplier": 1.45,
    },
    "w_frost_lance": {
        "id": "w_frost_lance",
        "display_name": "冰脊长枪",
        "archetype": "reach_melee",
        "base_damage": 36,
        "attack_interval": 0.74,
        "sense_radius": 380,
        "attack_range": 255,
        "attack_arc_deg": 62,
        "fire_tolerance_deg": 36,
        "windup_time": 0.14,
        "projectile_speed": 0,
        "projectile_lifetime": 0,
        "projectile_count": 1,
        "penetration": 5,
        "is_melee": True,
        "crit_chance": 0.10,
        "crit_multiplier": 1.75,
    },
    "w_flame_handcannon": {
        "id": "w_flame_handcannon",
        "display_name": "赤焰手炮",
        "archetype": "heavy_projectile",
        "base_damage": 64,
        "attack_interval": 0.95,
        "sense_radius": 760,
        "attack_range": 650,
        "attack_arc_deg": 28,
        "fire_tolerance_deg": 14,
        "windup_time": 0.20,
        "projectile_speed": 520,
        "projectile_lifetime": 1.35,
        "projectile_radius": 16,
        "projectile_count": 1,
        "penetration": 2,
        "splash_radius": 52,
        "is_melee": False,
        "requires_line_of_sight": True,
        "crit_chance": 0.12,
        "crit_multiplier": 1.9,
    },
    "w_starfall_bow": {
        "id": "w_starfall_bow",
        "display_name": "星坠弓",
        "archetype": "ranged_burst",
        "base_damage": 21,
        "attack_interval": 0.66,
        "sense_radius": 820,
        "attack_range": 720,
        "attack_arc_deg": 36,
        "fire_tolerance_deg": 16,
        "windup_time": 0.13,
        "projectile_speed": 680,
        "projectile_lifetime": 1.25,
        "projectile_radius": 7,
        "projectile_count": 3,
        "spread_arc_deg": 18,
        "penetration": 1,
        "is_melee": False,
        "requires_line_of_sight": True,
        "crit_chance": 0.11,
        "crit_multiplier": 1.65,
    },
    "w_venom_knife": {
        "id": "w_venom_knife",
        "display_name": "毒雾匕首",
        "archetype": "status_melee",
        "base_damage": 20,
        "attack_interval": 0.36,
        "sense_radius": 260,
        "attack_range": 125,
        "attack_arc_deg": 110,
        "fire_tolerance_deg": 65,
        "windup_time": 0.06,
        "projectile_speed": 0,
        "projectile_lifetime": 0,
        "projectile_count": 1,
        "penetration": 3,
        "is_melee": True,
        "crit_chance": 0.20,
        "crit_multiplier": 1.6,
    },
    "w_magnetic_ringblade": {
        "id": "w_magnetic_ringblade",
        "display_name": "磁暴环刃",
        "archetype": "boomerang_orb",
        "base_damage": 26,
        "attack_interval": 0.58,
        "sense_radius": 720,
        "attack_range": 620,
        "attack_arc_deg": 360,
        "fire_tolerance_deg": 90,
        "windup_time": 0.08,
        "projectile_speed": 430,
        "projectile_lifetime": 2.6,
        "projectile_radius": 13,
        "projectile_count": 1,
        "penetration": 6,
        "bounces": True,
        "bounce_count": 4,
        "is_melee": False,
        "crit_chance": 0.07,
        "crit_multiplier": 1.55,
    },
    "w_holy_scepter": {
        "id": "w_holy_scepter",
        "display_name": "圣辉权杖",
        "archetype": "support_beam",
        "base_damage": 24,
        "attack_interval": 0.48,
        "sense_radius": 700,
        "attack_range": 640,
        "attack_arc_deg": 24,
        "fire_tolerance_deg": 12,
        "windup_time": 0.11,
        "projectile_speed": 880,
        "projectile_lifetime": 0.8,
        "projectile_radius": 8,
        "projectile_count": 1,
        "penetration": 3,
        "beam_width": 9,
        "is_melee": False,
        "requires_line_of_sight": True,
        "crit_chance": 0.08,
        "crit_multiplier": 1.55,
    },
    "w_blood_scythe": {
        "id": "w_blood_scythe",
        "display_name": "血契镰刀",
        "archetype": "wide_melee",
        "base_damage": 52,
        "attack_interval": 0.92,
        "sense_radius": 360,
        "attack_range": 230,
        "attack_arc_deg": 190,
        "fire_tolerance_deg": 100,
        "windup_time": 0.18,
        "projectile_speed": 0,
        "projectile_lifetime": 0,
        "projectile_count": 1,
        "penetration": 8,
        "is_melee": True,
        "crit_chance": 0.09,
        "crit_multiplier": 2.05,
    },
    "w_void_pistols": {
        "id": "w_void_pistols",
        "display_name": "虚空双枪",
        "archetype": "rapid_dual",
        "base_damage": 13,
        "attack_interval": 0.18,
        "sense_radius": 690,
        "attack_range": 610,
        "attack_arc_deg": 42,
        "fire_tolerance_deg": 22,
        "windup_time": 0.03,
        "projectile_speed": 760,
        "projectile_lifetime": 0.88,
        "projectile_radius": 5,
        "projectile_count": 2,
        "spread_arc_deg": 10,
        "penetration": 1,
        "is_melee": False,
        "requires_line_of_sight": True,
        "crit_chance": 0.09,
        "crit_multiplier": 1.45,
    },
    "w_rockfall_hammer": {
        "id": "w_rockfall_hammer",
        "display_name": "岩崩战锤",
        "archetype": "shockwave_melee",
        "base_damage": 86,
        "attack_interval": 1.55,
        "sense_radius": 360,
        "attack_range": 260,
        "attack_arc_deg": 360,
        "fire_tolerance_deg": 120,
        "windup_time": 0.34,
        "projectile_speed": 0,
        "projectile_lifetime": 0,
        "projectile_count": 1,
        "penetration": 14,
        "is_melee": True,
        "clears_enemy_bullets": True,
        "crit_chance": 0.06,
        "crit_multiplier": 2.15,
    },
    "w_wind_tachi": {
        "id": "w_wind_tachi",
        "display_name": "风切太刀",
        "archetype": "wind_melee",
        "base_damage": 31,
        "attack_interval": 0.46,
        "sense_radius": 430,
        "attack_range": 210,
        "attack_arc_deg": 130,
        "fire_tolerance_deg": 76,
        "windup_time": 0.08,
        "projectile_speed": 0,
        "projectile_lifetime": 0,
        "projectile_count": 1,
        "penetration": 4,
        "is_melee": True,
        "crit_chance": 0.14,
        "crit_multiplier": 1.7,
    },
    "w_thunder_array": {
        "id": "w_thunder_array",
        "display_name": "四雷阵盘",
        "archetype": "thunder_orb",
        "base_damage": 38,
        "attack_interval": 0.82,
        "sense_radius": 760,
        "attack_range": 680,
        "attack_arc_deg": 360,
        "fire_tolerance_deg": 90,
        "windup_time": 0.16,
        "projectile_speed": 540,
        "projectile_lifetime": 1.6,
        "projectile_radius": 11,
        "projectile_count": 4,
        "spread_arc_deg": 34,
        "penetration": 2,
        "bounces": True,
        "bounce_count": 2,
        "is_melee": False,
        "crit_chance": 0.10,
        "crit_multiplier": 1.75,
    },
    "w_railbow": {
        "id": "w_railbow",
        "display_name": "磁轨长弓",
        "archetype": "charged_rail",
        "base_damage": 72,
        "attack_interval": 1.08,
        "sense_radius": 900,
        "attack_range": 860,
        "attack_arc_deg": 16,
        "fire_tolerance_deg": 8,
        "windup_time": 0.26,
        "projectile_speed": 1100,
        "projectile_lifetime": 1.2,
        "projectile_radius": 10,
        "projectile_count": 1,
        "penetration": 8,
        "beam_width": 14,
        "is_melee": False,
        "requires_line_of_sight": True,
        "crit_chance": 0.14,
        "crit_multiplier": 2.0,
    },
    "w_ember_drone": {
        "id": "w_ember_drone",
        "display_name": "熔核无人机",
        "archetype": "orbit_omni",
        "base_damage": 19,
        "attack_interval": 0.28,
        "sense_radius": 360,
        "attack_range": 210,
        "attack_arc_deg": 360,
        "fire_tolerance_deg": 90,
        "windup_time": 0.05,
        "projectile_speed": 0,
        "projectile_lifetime": 0,
        "projectile_count": 1,
        "penetration": 2,
        "is_melee": True,
        "omnidirectional": True,
        "crit_chance": 0.08,
        "crit_multiplier": 1.55,
    },
}


# =============================================================================
# 卡牌 —《抽卡系统》§7
# =============================================================================
DEFAULT_CARDS: dict[str, dict] = {
    # ----- 银色可叠加 -----
    "c_atk_plus": {
        "id": "c_atk_plus",
        "tier": "silver",
        "stackable": True,
        "weight": 16,
        "tags": ["offense"],
        "effects": [{"type": "dmg_pct", "value": 0.15}],
        "name_zh": "攻击强化",
        "rarity_zh": "银",
    },
    "c_speed_plus": {
        "id": "c_speed_plus",
        "tier": "silver",
        "stackable": True,
        "weight": 12,
        "tags": ["offense", "speed"],
        "effects": [{"type": "aspd_pct", "value": 0.12}],
        "name_zh": "快速装填",
        "rarity_zh": "银",
    },
    "c_range_plus": {
        "id": "c_range_plus",
        "tier": "silver",
        "stackable": True,
        "weight": 10,
        "tags": ["offense", "range"],
        "effects": [{"type": "range_pct", "value": 0.18}],
        "name_zh": "延伸攻击",
        "rarity_zh": "银",
    },
    "c_arc_plus": {
        "id": "c_arc_plus",
        "tier": "silver",
        "stackable": True,
        "weight": 10,
        "tags": ["offense", "range"],
        "effects": [{"type": "arc_deg", "value": 20}, {"type": "tol_deg", "value": 5}],
        "name_zh": "宽幅攻击",
        "rarity_zh": "银",
    },
    "c_hp_plus": {
        "id": "c_hp_plus",
        "tier": "silver",
        "stackable": True,
        "weight": 12,
        "tags": ["defense"],
        "effects": [{"type": "max_hp_flat", "value": 20}, {"type": "current_hp_flat", "value": 20}],
        "name_zh": "强健核心",
        "rarity_zh": "银",
    },
    "c_shield_restore": {
        "id": "c_shield_restore",
        "tier": "silver",
        "stackable": True,
        "weight": 6,
        "tags": ["defense"],
        "effects": [{"type": "shield_flat", "value": 30}],
        "name_zh": "护盾补充",
        "rarity_zh": "银",
    },
    "c_pickup_plus": {
        "id": "c_pickup_plus",
        "tier": "silver",
        "stackable": True,
        "weight": 8,
        "tags": ["utility"],
        "effects": [{"type": "pickup_radius_pct", "value": 0.25}],
        "name_zh": "拾取扩展",
        "rarity_zh": "银",
    },
    "c_armor_plus": {
        "id": "c_armor_plus",
        "tier": "silver",
        "stackable": True,
        "weight": 5,
        "tags": ["defense"],
        "effects": [{"type": "armor_flat", "value": 4}],
        "name_zh": "加固装甲",
        "rarity_zh": "银",
    },
    "c_move_plus": {
        "id": "c_move_plus",
        "tier": "silver",
        "stackable": True,
        "weight": 6,
        "tags": ["utility"],
        "effects": [{"type": "move_speed_pct", "value": 0.08}],
        "name_zh": "迅捷步伐",
        "rarity_zh": "银",
    },
    "c_penetration": {
        "id": "c_penetration",
        "tier": "silver",
        "stackable": True,
        "weight": 5,
        "tags": ["offense"],
        "effects": [{"type": "penetration", "value": 1}],
        "name_zh": "穿透组件",
        "rarity_zh": "银",
    },
    "c_xp_gain": {
        "id": "c_xp_gain",
        "tier": "silver",
        "stackable": True,
        "weight": 6,
        "tags": ["utility"],
        "effects": [{"type": "xp_gain_pct", "value": 0.20}],
        "name_zh": "汲取经验",
        "rarity_zh": "银",
    },
    # ----- 金色 -----
    "c_new_weapon": {
        "id": "c_new_weapon",
        "tier": "gold",
        "stackable": False,
        "weight": 5,
        "tags": ["weapon"],
        "effects": [{"type": "gain_random_weapon"}],
        "name_zh": "新武器",
        "rarity_zh": "金",
    },
    "c_active_weapon_levelup": {
        "id": "c_active_weapon_levelup",
        "tier": "gold",
        "stackable": True,
        "weight": 6,
        "tags": ["weapon", "upgrade"],
        "effects": [{"type": "active_weapon_level_up"}],
        "applies_to_weapon": "active",  # 锁定激活武器
        "name_zh": "当前武器升级",
        "rarity_zh": "金",
    },
    "c_heavy_atk": {
        "id": "c_heavy_atk",
        "tier": "gold",
        "stackable": True,
        "weight": 4,
        "tags": ["offense"],
        "effects": [{"type": "dmg_pct", "value": 0.35}],
        "name_zh": "强力增幅",
        "rarity_zh": "金",
    },
    "c_sniper_calibrate": {
        "id": "c_sniper_calibrate",
        "tier": "gold",
        "stackable": True,
        "weight": 4,
        "tags": ["offense", "range"],
        "effects": [
            {"type": "range_pct", "value": 0.30, "scope": "active_weapon"},
            {"type": "tol_deg", "value": 8, "scope": "active_weapon"},
        ],
        "applies_to_weapon": "active",
        "name_zh": "远距校准",
        "rarity_zh": "金",
    },
    "c_multishot": {
        "id": "c_multishot",
        "tier": "gold",
        "stackable": True,
        "weight": 3,
        "tags": ["offense"],
        "effects": [
            {"type": "extra_projectile", "value": 1, "dmg_share": 0.45},
        ],
        "name_zh": "多重发射",
        "rarity_zh": "金",
    },
    "c_compound_armor": {
        "id": "c_compound_armor",
        "tier": "gold",
        "stackable": True,
        "weight": 4,
        "tags": ["defense"],
        "effects": [
            {"type": "max_hp_flat", "value": 35},
            {"type": "armor_flat", "value": 15},
        ],
        "name_zh": "复合装甲",
        "rarity_zh": "金",
    },
    "c_regen_shield": {
        "id": "c_regen_shield",
        "tier": "gold",
        "stackable": True,
        "weight": 3,
        "tags": ["defense"],
        "effects": [
            {"type": "max_shield_flat", "value": 60},
            {"type": "shield_regen_unlocked", "rate": 6.0},
        ],
        "name_zh": "再生护盾",
        "rarity_zh": "金",
    },
    "c_desperation": {
        "id": "c_desperation",
        "tier": "gold",
        "stackable": True,
        "weight": 3,
        "tags": ["offense", "utility"],
        "effects": [
            {"type": "low_hp_atk_pct", "value": 0.40, "threshold": 0.35},
            {"type": "low_hp_move_pct", "value": 0.15, "threshold": 0.35},
        ],
        "name_zh": "危急反击",
        "rarity_zh": "金",
    },
    # ----- 彩色（每局唯一） -----
    "c_prism_shot": {
        "id": "c_prism_shot",
        "tier": "color",
        "stackable": False,
        "weight": 1.5,
        "tags": ["weapon", "unique"],
        "effects": [{"type": "prism_flare", "value": 0.45, "count": 2}],
        "name_zh": "棱镜齐射",
        "rarity_zh": "彩",
        "unique_per_run": True,
    },
    "c_global_sense": {
        "id": "c_global_sense",
        "tier": "color",
        "stackable": False,
        "weight": 1.5,
        "tags": ["offense", "unique"],
        "effects": [
            {"type": "turn_speed_pct", "value": 1.00},
            {"type": "range_pct", "value": 0.20, "scope": "active_weapon"},
        ],
        "name_zh": "全域感知",
        "rarity_zh": "彩",
        "unique_per_run": True,
    },
    "c_invuln_shell": {
        "id": "c_invuln_shell",
        "tier": "color",
        "stackable": False,
        "weight": 1.5,
        "tags": ["defense", "unique"],
        "effects": [
            {"type": "max_shield_flat", "value": 100},
            {"type": "break_invuln", "duration": 1.0, "cooldown": 20.0},
        ],
        "name_zh": "不灭屏障",
        "rarity_zh": "彩",
        "unique_per_run": True,
    },
    "c_rainbow_core": {
        "id": "c_rainbow_core",
        "tier": "color",
        "stackable": False,
        "weight": 0.5,
        "tags": ["offense", "defense", "unique"],
        "effects": [
            {"type": "dmg_pct", "value": 0.40},
            {"type": "aspd_pct", "value": 0.30},
            {"type": "max_hp_pct", "value": 0.30},
        ],
        "name_zh": "彩色核心",
        "rarity_zh": "彩",
        "unique_per_run": True,
    },
    "c_laser_cannon": {
        "id": "c_laser_cannon",
        "tier": "color",
        "stackable": False,
        "weight": 0.8,
        "tags": ["weapon", "unique"],
        "effects": [{"type": "gain_weapon", "weapon_id": "w_laser_cannon"}],
        "name_zh": "超重型激光炮",
        "rarity_zh": "彩",
        "unique_per_run": True,
    },
    "c_great_cleaver": {
        "id": "c_great_cleaver",
        "tier": "color",
        "stackable": False,
        "weight": 3.0,
        "tags": ["weapon", "mechanic", "unique"],
        "effects": [{"type": "gain_weapon", "weapon_id": "w_great_cleaver"}],
        "name_zh": "裂地大砍刀",
        "description_zh": "高伤害、大范围并能斩落敌弹，但攻击速度明显降低。",
        "rarity_zh": "彩",
        "unique_per_run": True,
    },
    "c_ricochet_ball": {
        "id": "c_ricochet_ball",
        "tier": "color",
        "stackable": False,
        "weight": 3.0,
        "tags": ["weapon", "mechanic", "unique"],
        "effects": [{"type": "gain_weapon", "weapon_id": "w_ricochet_ball"}],
        "name_zh": "棱镜弹球",
        "description_zh": "弹体会在屏幕边缘连续反弹，并可穿过多个敌人。",
        "rarity_zh": "彩",
        "unique_per_run": True,
    },
    "c_railbow": {
        "id": "c_railbow",
        "tier": "color",
        "stackable": False,
        "weight": 2.0,
        "tags": ["weapon", "unique"],
        "effects": [{"type": "gain_weapon", "weapon_id": "w_railbow"}],
        "name_zh": "磁轨长弓",
        "description_zh": "蓄力发射高穿透磁轨箭，适合清理直线上的精英敌人。",
        "rarity_zh": "彩",
        "unique_per_run": True,
    },
    "c_ember_drone": {
        "id": "c_ember_drone",
        "tier": "color",
        "stackable": False,
        "weight": 2.0,
        "tags": ["weapon", "unique"],
        "effects": [{"type": "gain_weapon", "weapon_id": "w_ember_drone"}],
        "name_zh": "熔核无人机",
        "description_zh": "无人机围绕玩家持续清理近身威胁，适合移动作战。",
        "rarity_zh": "彩",
        "unique_per_run": True,
    },
    # 占位卡：用于合法池不足 3 张时补足。
    "c_filler_atk": {
        "id": "c_filler_atk",
        "tier": "silver",
        "stackable": True,
        "weight": 1,
        "tags": ["offense", "filler"],
        "effects": [{"type": "dmg_pct", "value": 0.05}],
        "name_zh": "细微改良",
        "rarity_zh": "银",
    },
}


# =============================================================================
# 掉落表 —《掉落系统》§2, §3
# =============================================================================
DEFAULT_DROP_TABLES: dict[str, dict] = {
    "std_drops": {
        "id": "std_drops",
        "entries": [
            {"kind": "xp_small", "amount": 1, "weight": 30, "icon": "xp"},
            {"kind": "xp_small", "amount": 3, "weight": 16, "icon": "xp"},
            {"kind": "heal", "pct_of_maxhp": 0.12, "min_amount": 8, "weight": 12, "icon": "heal"},
            {"kind": "armor", "amount": 1, "weight": 7, "icon": "armor"},
            {"kind": "coin", "amount": 1, "weight": 8, "icon": "coin"},
            {"kind": "coin", "amount": 3, "weight": 3, "icon": "coin"},
            {"kind": "temp_buff", "buff": "speed+15%", "duration": 5.0, "weight": 6, "icon": "buff"},
            {"kind": "temp_buff", "buff": "aspd+15%", "duration": 5.0, "weight": 4, "icon": "buff"},
            {"kind": "shield_restore", "amount": 15, "weight": 5, "icon": "shield"},
            {"kind": "hazard_bomb", "radius": 120, "damage": 18, "windup": 2.5, "weight": 9, "icon": "bomb"},
        ],
    },
    "super_drops": {
        "id": "super_drops",
        "entries": [
            {"kind": "xp_small", "amount": 8, "weight": 50, "icon": "xp"},
            {"kind": "heal", "pct_of_maxhp": 0.30, "min_amount": 30, "weight": 20, "icon": "heal"},
            {"kind": "armor", "amount": 3, "weight": 12, "icon": "armor"},
            {"kind": "coin", "amount": 12, "weight": 25, "icon": "coin"},
            {"kind": "shield_restore", "amount": 40, "weight": 20, "icon": "shield"},
            {"kind": "hazard_bomb", "radius": 120, "damage": 22, "windup": 2.5, "weight": 10, "icon": "bomb"},
        ],
    },
}


# =============================================================================
# 成就 —《成就系统》§3  共 24 个
# =============================================================================
DEFAULT_ACHIEVEMENTS: dict[str, dict] = {
    # A. 单局击杀分
    "ACH-RUNSCORE-I":  {"id": "ACH-RUNSCORE-I",  "series": "RUNSCORE", "grade": 1, "threshold": 2_000,   "metric": "run_score"},
    "ACH-RUNSCORE-II": {"id": "ACH-RUNSCORE-II", "series": "RUNSCORE", "grade": 2, "threshold": 20_000,  "metric": "run_score"},
    "ACH-RUNSCORE-III":{"id": "ACH-RUNSCORE-III","series": "RUNSCORE", "grade": 3, "threshold": 100_000, "metric": "run_score"},
    # B. 累计击杀分
    "ACH-TOTALSCORE-I":  {"id": "ACH-TOTALSCORE-I",  "series": "TOTALSCORE", "grade": 1, "threshold": 10_000,    "metric": "lifetime_score"},
    "ACH-TOTALSCORE-II": {"id": "ACH-TOTALSCORE-II", "series": "TOTALSCORE", "grade": 2, "threshold": 100_000,   "metric": "lifetime_score"},
    "ACH-TOTALSCORE-III":{"id": "ACH-TOTALSCORE-III","series": "TOTALSCORE", "grade": 3, "threshold": 1_000_000, "metric": "lifetime_score"},
    # C. 单局击杀数
    "ACH-RUNKILL-I":  {"id": "ACH-RUNKILL-I",  "series": "RUNKILL", "grade": 1, "threshold": 200,   "metric": "kills_run"},
    "ACH-RUNKILL-II": {"id": "ACH-RUNKILL-II", "series": "RUNKILL", "grade": 2, "threshold": 1_000, "metric": "kills_run"},
    "ACH-RUNKILL-III":{"id": "ACH-RUNKILL-III","series": "RUNKILL", "grade": 3, "threshold": 5_000, "metric": "kills_run"},
    # D. 超级怪兽
    "ACH-SUPER-I":  {"id": "ACH-SUPER-I",  "series": "SUPER", "grade": 1, "threshold": 1,   "metric": "super_kills_lifetime"},
    "ACH-SUPER-II": {"id": "ACH-SUPER-II", "series": "SUPER", "grade": 2, "threshold": 20,  "metric": "super_kills_lifetime"},
    "ACH-SUPER-III":{"id": "ACH-SUPER-III","series": "SUPER", "grade": 3, "threshold": 100, "metric": "super_kills_lifetime"},
    # E. 关卡 / 无尽
    "ACH-STAGE-I":   {"id": "ACH-STAGE-I",   "series": "STAGE", "grade": 1, "threshold": 1, "metric": "stage_reached", "value": 1},
    "ACH-STAGE-II":  {"id": "ACH-STAGE-II",  "series": "STAGE", "grade": 2, "threshold": 1, "metric": "campaign_cleared"},
    "ACH-STAGE-III": {"id": "ACH-STAGE-III", "series": "STAGE", "grade": 3, "threshold": 10, "metric": "endless_cycles"},
    # F. 无伤
    "ACH-NOHIT-I":  {"id": "ACH-NOHIT-I",  "series": "NOHIT", "grade": 1, "threshold": 60,  "metric": "no_damage_max_run"},
    "ACH-NOHIT-II": {"id": "ACH-NOHIT-II", "series": "NOHIT", "grade": 2, "threshold": 180, "metric": "no_damage_max_run"},
    "ACH-NOHIT-III":{"id": "ACH-NOHIT-III","series": "NOHIT", "grade": 3, "threshold": 600, "metric": "no_damage_max_run"},
    # G. 炸弹躲避
    "ACH-BOMB-I":  {"id": "ACH-BOMB-I",  "series": "BOMB", "grade": 1, "threshold": 10,  "metric": "bomb_dodges_lifetime"},
    "ACH-BOMB-II": {"id": "ACH-BOMB-II", "series": "BOMB", "grade": 2, "threshold": 100, "metric": "bomb_dodges_lifetime"},
    "ACH-BOMB-III":{"id": "ACH-BOMB-III","series": "BOMB", "grade": 3, "threshold": 500, "metric": "bomb_dodges_lifetime"},
    # H. 卡组成长
    "ACH-CARD-I":  {"id": "ACH-CARD-I",  "series": "CARD", "grade": 1, "threshold": 10,  "metric": "cards_run"},
    "ACH-CARD-II": {"id": "ACH-CARD-II", "series": "CARD", "grade": 2, "threshold": 50,  "metric": "cards_run"},
    "ACH-CARD-III":{"id": "ACH-CARD-III","series": "CARD", "grade": 3, "threshold": 200, "metric": "cards_run"},
}

for _aid, _cfg in DEFAULT_ACHIEVEMENTS.items():
    _grade_name = {1: "银色", 2: "金色", 3: "彩色"}.get(_cfg["grade"], "银色")
    _series_name = {
        "RUNSCORE": "分数达人",
        "TOTALSCORE": "累积分王",
        "RUNKILL": "清场专家",
        "SUPER": "首领猎手",
        "STAGE": "通关达人",
        "NOHIT": "无伤行者",
        "BOMB": "拆弹大师",
        "CARD": "集卡大师",
    }.get(_cfg["series"], _cfg["series"])
    _cfg.setdefault("name_zh", f"{_series_name}·{_grade_name}")
    _cfg.setdefault("tier_zh", _grade_name.replace("色", ""))
    _cfg.setdefault("description_zh", f"达成 {_series_name} 第 {_cfg['grade']} 档")


# =============================================================================
# 开局预设 —《开局预设》
# =============================================================================
DEFAULT_PRESETS: dict[str, dict] = {
    "preset_balanced": {
        "id": "preset_balanced",
        "display_name": "默认武器配置",
        "description_zh": "默认账号武器配置：由开局武器界面决定",
        "attributes": {
            "max_hp": 110,
            "move_speed": 320,
            "armor": 1,
            "pickup_radius": 110,
            "max_shield": 0,
            "current_shield": 0,
        },
        "weapon_stack": ["w_rifle_precise", "w_melee_blade"],
        "active_weapon": "w_rifle_precise",
        "starting_card_pool": ["c_hp_plus"],
    },
    "preset_melee": {
        "id": "preset_melee",
        "display_name": "兼容配置A",
        "description_zh": "兼容旧存档的内部配置",
        "attributes": {
            "max_hp": 130,
            "move_speed": 300,
            "armor": 2,
            "pickup_radius": 110,
            "max_shield": 0,
            "current_shield": 0,
        },
        "weapon_stack": ["w_melee_blade", "w_orbiter_omni"],
        "active_weapon": "w_melee_blade",
        "starting_card_pool": ["c_compound_armor"],
    },
    "preset_sniper": {
        "id": "preset_sniper",
        "display_name": "兼容配置B",
        "description_zh": "兼容旧存档的内部配置",
        "attributes": {
            "max_hp": 95,
            "move_speed": 340,
            "armor": 0,
            "pickup_radius": 110,
            "max_shield": 0,
            "current_shield": 0,
        },
        "weapon_stack": ["w_shotgun_spread", "w_arcane_orb"],
        "active_weapon": "w_shotgun_spread",
        "starting_card_pool": ["c_speed_plus"],
    },
}


def load_default_bundle() -> ConfigBundle:
    """加载默认配置并执行校验。"""
    bundle = ConfigBundle(
        enemies=DEFAULT_ENEMIES,
        weapons=DEFAULT_WEAPONS,
        cards=DEFAULT_CARDS,
        drop_tables=DEFAULT_DROP_TABLES,
        presets=DEFAULT_PRESETS,
        stages=DEFAULT_STAGES,
        achievements=DEFAULT_ACHIEVEMENTS,
        schema_version="0.1.0",
        config_version="0.1.0",
    )
    validate_config_bundle(bundle)
    return bundle
